### ISSUE TITLE
DOC: fixture duration top

### ISSUE THREAD

**Issue by martin-thoma** [blake-r/pytest-durations#13]
In the example report of https://pypi.org/project/pytest-durations/ I see `https://pypi.org/project/pytest-durations/`, but when I execute pytest with `--durations 10` I only see the test execution time.

I would be very interested in fixtures (how often are they excecuted? How much time was spent in total/average executing a given fixture?)

**Comment by blake-r** [comment]
Hi Martin! Perhaps, there is a misunderstanding between pytest's built-in "durations" and pytest-duration's plugin functionalities.

When you use `--durations`, it enables pytest's build-in functionality to measure test execution time.

If you have [pytest-durations plugin](https://pypi.org/project/pytest-durations/) installed, it will automatically output test setup time per fixture in addition to test durations. To control the number of output lines, you can use `--pytest-durations` flag.

I hope, the explanation helps. Feel free to contact me otherwise.

I will also be thankful if you contact me in case of your question solvation, to close the issue.

**Comment by martin-thoma** [comment]
Thank you <3 I think that answered it :-)
